FROM ianhorn/nanoserver:1.0.0

WORKDIR /app
COPY . /app

RUN pip install -r requirements.txt && \
    python -m pip install pypgstac && \
    python -m pip install "psycopg[binary,pool]"

RUN python -m pip install -e .[dev,server] --user
